framework:
    messenger:
        failure_transport: failed

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 5000 # milliseconds delay
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            doctrine: 'doctrine://default'

        routing:
            # Route your messages to the transports
            'App\Messenger\DoSomething': async
