framework:
    messenger:
        failure_transport: failed

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    cacert: '%env(MESSENGER_CACERT_PATH)%'
                    delay:
                        queue_name_pattern: '%%exchange_name%%_%%routing_key%%_delay_%%delay%%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000 # milliseconds delay
                    multiplier: 1

            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            doctrine: 'doctrine://default'

        routing:
            # Route your messages to the transports
            'App\Messenger\DoSomething': async
