version: "3.7"
services:
    php:
        image: rabbitmq-playground
        build: .
        volumes:
            - .:/app
            - .docker/entrypoint.sh:/entrypoint.sh
        working_dir: /app
        entrypoint: [ "/entrypoint.sh" ]
        depends_on:
            - postgres
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3

    worker:
        image: rabbitmq-playground
        volumes:
            - .:/app
        working_dir: /app
        command: [ "bin/console", "messenger:consume" ]
        depends_on:
            - postgres
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3

    postgres:
        # alpine is forbidden => https://stackoverflow.com/questions/58135353/postgres-seems-to-be-ignoring-my-default-collation
        image: postgres:13
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: test
        volumes:
            - .docker-data/postgres:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT:-5432}:5432"

    adminer:
        image: adminer:4.8.0
        ports:
            - "${ADMINER_PORT:-8000}:8080"
        depends_on:
            - postgres

    rabbitmq1:
        image: bitnami/rabbitmq:3.9
        restart: unless-stopped
        environment:
            - RABBITMQ_NODE_TYPE=stats
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
            - RABBITMQ_LOGS=-
        ports:
            - "15672:15672"
        volumes:
            - .docker-data/rabbitmq1:/bitnami

    rabbitmq2:
        image: bitnami/rabbitmq:3.9
        restart: unless-stopped
        environment:
            - RABBITMQ_NODE_TYPE=queue-disc
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
            - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
            - RABBITMQ_LOGS=-
        volumes:
            - .docker-data/rabbitmq2:/bitnami

    rabbitmq3:
        image: bitnami/rabbitmq:3.9
        restart: unless-stopped
        environment:
            - RABBITMQ_NODE_TYPE=queue-ram
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
            - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
            - RABBITMQ_LOGS=-
        volumes:
            - .docker-data/rabbitmq3:/bitnami
